# forum / bounty
max_body_length = 250
max_body_lines = 6
max_title_length = 50
long_multiplier = 2   # multiply above params by this value when link prefixed with !

max_tries = 3             # for pages that require login (namely bounties)
hath_value = 3700
fail_reaction_emote = "âŒ"

thread_title_template = '''
  {{TITLE}}
'''

thread_body_template = '''
  {{SUB_TITLE}}
  ```fix
  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d"|format(YEAR)}}-{{"%02d"|format(MONTH)}}-{{"%02d"|format(DAY)}} | {{FORUM|truncate(15,True)}}
'''

comment_title_template = '''
  {{TITLE}}
'''

comment_body_template = '''
  ```fix
  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d"|format(YEAR)}}-{{"%02d"|format(MONTH)}}-{{"%02d"|format(DAY)}} | {{FORUM|truncate(15,True)}}
'''

bounty_title_template = '''
  {{TITLE}}
'''

bounty_body_template = '''
  ```css
  [ {{TYPE}} | ~{{CREDIT_VALUE}} Credits | {{STATUS}} ]

  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d-%02d-%02d"|format(YEAR,MONTH,DAY)}}
'''

# HV equips
# stat names are case-insensitive and generally follow the original naming scheme with the following exceptions:
#  mitigations are suffixed with MIT
#  attack damage is suffixed with ADB
#  spell damage is suffixed with EDB
#  proficiency is suffixed with PROF
[equip]
only_legendary_ranges = true

min_percentile = 75 # show non-mandatory stats above this percentile

[equip.mandatory_stats] # "(partial) equip name" = [list of (partial) mandatory stat names]
"" = ["block", "parry"]
staff = ["magic damage", "depr prof", "int", "wis"]

"fiery staff" = ["fire edb"]
"arctic staff" = ["cold edb"]
"temp staff" = ["wind edb"]
"shock staff" = ["elec edb"]
"hallowed staff" = ["holy edb"]
"demon staff" = ["dark edb"]

surtr = ["fire edb", "elem prof"]
nifl = ["cold edb", "elem prof"]
freyr = ["wind edb", "elem prof"]
mjo = ["elec edb", "elem prof"]
heimd = ["holy edb", "div prof"]
fenr = ["dark edb", "forb prof"]

"the elem" = ["elem prof"]
"the demon" = ["forb prof"]
"the heaven" = ["div prof"]

waki = ["attack damage"]
axe = ["attack damage"]
club = ["attack damage"]
rapier = ["attack damage"]
sword = ["attack damage"]
estoc = ["attack damage"]
mace = ["attack damage"]
katana = ["attack damage"]

leather = ["strength", "dex", "end"]
shade = ["strength", "dex", "end", "attack damage"]
plate = ["strength", "dex", "end"]
power = ["strength", "dex", "end", "attack damage"]

# keys must match table_categories --- also keep "other"
[table_headers]
offensive = "Offensive"
defensive = "Defensive"
#    supportive= Supportive
#    pabs= PABs
other = "Other"

# keys must match table_headers
[table_categories]
offensive = [
  "damage",
  "edb",
  "crit",
  "intelligence",
  "wisdom",
  "strength",
  "dexterity",
]
defensive = ["parry", "mit", "agility", "endurance"]
# supportive= [prof, accuracy]
#    pabs= [wisdom, intelligence, dexterity, strength, agility, endurance]
other = []

# case sensitive mappings (html name --> desired abbreviation)
[abbreviations]
"Block Chance" = "BLK"
"Attack Damage" = "ADB"
"Magic Damage" = "MDB"
"Attack Crit Chance" = "Pcrit%"
"Magic Crit Chance" = "Mcrit%"
"Attack Crit Damage" = "Pcrit Dmg"
"Magic Crit Damage" = "Mcrit Dmg"
"Attack Accuracy" = "Pacc"
"Magic Accuracy" = "Macc"

"Elemental PROF" = "Elem Prof"
"Supportive PROF" = "Supp Prof"
"Deprecating PROF" = "Depr Prof"
"Divine PROF" = "Holy Prof"
"Forbidden PROF" = "Dark Prof"

"Wisdom" = "WIS"
"Intelligence" = "INT"
"Agility" = "AGI"
"Endurance" = "END"
"Strength" = "STR"
"Dexterity" = "DEX"

"Interference" = "Intf"

"Physical Mitigation" = "Pmit"
"Magical Mitigation" = "Mmit"
"Crushing MIT" = "Crush"
"Slashing MIT" = "Slash"
"Piercing MIT" = "Pierc"

"Parry Chance" = "Parry"
"Evade Chance" = "Evade"
"Resist Chance" = "Resist"
"Counter-Resist" = "CR"
"Attack Speed" = "AS"
"Casting Speed" = "CS"
